version: 0.2
phases:
  pre_build:
    commands:
      - echo "Logging into Amazon ECR"
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/l2t9w8o1
  build:
    commands:
      - echo "Build started on `date`"
      - echo "Building the Docker image"          
      - docker build -t echocloud .
      - docker tag echocloud:latest public.ecr.aws/l2t9w8o1/echocloud:latest
  post_build:
    commands:
      - echo "Pushing the Docker image to ECR"
      - docker push public.ecr.aws/l2t9w8o1/echocloud:latest
      - echo "Build completed on `date`"